interface=wlp2s0
driver=nl80211
ssid=Solis-Setup
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1
country_code=IE
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_passphrase=ChangeMe1234
rsn_pairwise=CCMP
ignore_broadcast_ssid=0
